#!/bin/bash
DOCKER_VM=vm
eval docker-machine create -d virtualbox $DOCKER_VM
eval docker-machine start $DOCKER_VM
eval `docker-machine env $DOCKER_VM`
eval docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --rm -v `pwd`:/workspace -it 0x0584/prog-mode
